server:
  port: 80


# druid连接池配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reggie?useSSL=false
    username: root
    password: 1qaz2wsxE
    driver-class-name: com.mysql.cj.jdbc.Driver

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000

    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID


reggie:
  path: /Users/liao/Desktop/JAVA/RuiJi/ruiji-img/
